### PR TITLE
feature fix for #32, map only first n rows

### PR DESCRIPTION
**Pull request by jigarWala**
Feature #32  Map only first n rows
Tested on both XSSF & HSSF excels. Please review it and do let me know if I am missing anything @ozlerhakan 

Thanks for this wonderful library :smile:

### CODE REVIEW

**Comment by jigarWala** [comment]
Hi @ozlerhakan  I have updated the limitting logic. let me know if I am missing something
Thankyou

**Comment by jigarWala** [comment]
I don't know why the build is failing? I didn't touched any other file

**Comment by ozlerhakan** [comment]
thanks @jigarWala merged!

**Comment by jigarWala** [comment]
you're welcome :smile:

**Pull request merged**
