### PR TITLE
This commit addresses the following issues:

### PR DESCRIPTION
**Pull request by chinmay1994**
1. Fix issue where row and column is not sent to the casting interface.
2. Fix issue where the setValue() method is called twice.

### CODE REVIEW

**Comment by ozlerhakan** [comment]
Oh, hey @chinmay1994 , I am just releasing the new version with the fix for your issue 😅

**Comment by chinmay1994** [comment]
> Oh, hey @chinmay1994 , I am just releasing the new version with the fix for your issue 😅

Haha, great! Does it include fix both the issues?

**Comment by ozlerhakan** [comment]
I will add your changes as well 👏

**Comment by chinmay1994** [comment]
Thank you @ozlerhakan 😊

**Pull request merged**
