### PR TITLE
Issue 185 default system locale gives different behavior

### PR DESCRIPTION
**Pull request by bendh**
fixes issue #185

### CODE REVIEW

**Comment by bendh** [comment]
@ozlerhakan Hello Hakan, do you have any timeline when this will be released so we can use it from Maven?

**Comment by ozlerhakan** [comment]
Hi @bendh , thank you for your changes. We can have it in the next release. I have a plan to do it this weekend. Could you also pinpoint on the README file for this feature?

**Comment by bendh** [comment]
> Hi @bendh , thank you for your changes. We can have it in the next release. I have a plan to do it this weekend. Could you also pinpoint on the README file for this feature?

That would be great! I added the feature to the readme with some background information

**Comment by ozlerhakan** [comment]
thanks @bendh

**Pull request merged**
