### PR TITLE
Added Consumer Java 8 feature

### PR DESCRIPTION
**Pull request by fmarazita**
Hi Ozler,

thanks a lot for your email. I have submitted the modifications, please contact me if you have any question.

Thanks a lot
Fabrizio

### CODE REVIEW

**Comment by fmarazita** [comment]
Hi Ozler,

I forgot to change
.travis.yml -> deleting the Java 7

Alle the best
Fabrizio

**Comment by ozlerhakan** [comment]
Hi @fmarazita ,

Could you give me an example usage for that case, so that I can mention it on README?

**Comment by fmarazita** [comment]
I think you can explain that this feature is very usefull for:

- Huge excel file ( without you have all in memory)
- Run time processing/ filtering data
- DB batch insertion

Calculation class
-  @ExcelCell(0) String Name
-  @ExcelCell(1) int a
-  @ExcelCell(2) int b

In Main:
File fileCalculation = new File(example.xlsx);
PoijiOptions options = PoijiOptionsBuilder.settings(1).sheetIndex(1).build();
Poiji.fromExcel(fileCalculation, Calculation.class, options, this::dbInsertion);


Function dbInsertion
private void dbInsertion(Calculation siCalculation) {
   int value= siCalculation.getA() + siCalculation.getB();
   int  name = siCalculation.getName();  
   return insertDB(name , value);
}

Thanks a lot for your time!!

**Comment by fmarazita** [comment]
Sorry @ozlerhakan I clicked on the Close and comment instead of Comment

**Comment by ozlerhakan** [comment]
Thank you for the detailed examples @fmarazita

**Comment by ozlerhakan** [comment]
Thanks @fmarazita merged!

**Comment by fmarazita** [comment]
@ozlerhakan thanks a lot for your collaboration!

**Pull request merged**
