### PR TITLE
Feature: Map unknown cells to map

### PR DESCRIPTION
**Pull request by breucode**
The new @ExcelUnknownCells annotation can be put on a Map<String, String> to put all cell contents into it, which are not mapped in any other way.

This is based on the commit from MR #114, so #114 should be merged first.

### CODE REVIEW

**Comment by breucode** [comment]
Documentation is missing. Currently adding it.

**Comment by breucode** [comment]
Tests missing for the case, that multiple identical headers are present for the unknown cells

**Comment by breucode** [comment]
Documentation added

**Comment by breucode** [comment]
Ready to be merged. I have no clue, why coveralls says, that the coverage dropped, but only tells me that coverage increased or stayed the same on a file level.

**Comment by ozlerhakan** [comment]
thank you for this new feature @breucode

**Comment by ozlerhakan** [comment]
merged @breucode

**Comment by gvh1234** [comment]
Hi there, can I ask you to explain what the following is trying to solve?
Why the @ symbol?
many thanks

```
    private String getTitleNameForMap(String cellContent, int columnIndex) {
        String titleName;
        if (titlePerColumnIndex.containsValue(cellContent)
                || cellContent.isEmpty()) {
            titleName = cellContent + "@" + columnIndex;
        } else {
            titleName = cellContent;
        }
        return titleName;
    }
```

**Comment by breucode** [comment]
This is needed, when you have the same header field multiple times. The first column with that header will get "headerName" and the subsequent headers will get "headerName@column".

Have a look at https://github.com/breucode/poiji/blob/c811a314501a9df3d4a541319446b49f61786010/src/test/java/com/poiji/deserialize/UnknownCellsIdenticalHeadersTest.java and the corresponding excel file https://github.com/breucode/poiji/blob/c811a314501a9df3d4a541319446b49f61786010/src/test/resources/unknown-cells-identical-headers.xlsx 

I hope I was able to help :)

**Comment by gvh1234** [comment]
Thank for your very quick reply.

I am parsing a messy Sheet where there are 2 lines of headers. Some of the column headers are duplicated on lines 0 and 1.

So I want to start on line 1 and I am using .headerStart(1)  in the options builder.
So I was hoping it would completely ignore line 0

But this code in PoijiHandler seems to be using both lines 0 and 1 to build up headers.
I think the **_if_** statement might need thinking about?


```    
public void cell(String cellReference, String formattedValue, XSSFComment comment) {
        CellAddress cellAddress = new CellAddress(cellReference);
        int row = cellAddress.getRow();
        int headers = options.getHeaderStart();
        int column = cellAddress.getColumn();
        if (row <= headers) {
               columnIndexPerTitle.put(.........
```

**Comment by breucode** [comment]
Yep that looks like a bug. I think it should be something like (row == headers).

What would you say @ozlerhakan ?

**Pull request merged**
