### PR TITLE
Added new change to read excel file by sheet name

### PR DESCRIPTION
**Pull request by 4sujittiwari**

### CODE REVIEW

**Comment by 4sujittiwari** [comment]
#73

**Comment by ozlerhakan** [comment]
Thanks @4sujittiwari ,I will look at the changes soon.

**Comment by ozlerhakan** [comment]
sorry @4sujittiwari , I haven't looked at it yet

**Comment by AdrienHorgnies** [comment]
It will be a nice feature.

**Comment by AdrienHorgnies** [comment]
@4sujittiwari I gave a quick look on the PR. You've mixed spaces and tabs indentation. Could you indent with spaces everywhere ? That would make the code easier to read on Github.

**Comment by 4sujittiwari** [comment]
> @4sujittiwari I gave a quick look at the PR. You've mixed spaces and tabs indentation. Could you indent with spaces everywhere, please ? That would make the code easier to read on Github.

Sure @AdrienHorgnies ...

**Comment by ozlerhakan** [comment]
thanks @4sujittiwari , merged!

**Pull request merged**
