### PR TITLE
Fix Parsing decimal value in other locales than "en" produces 0.0 (#91)

### PR DESCRIPTION
**Pull request by hexmind**

### CODE REVIEW

**Comment by ozlerhakan** [comment]
Hi @hexmind , thank for your work! keep in mind that we need to increment the current coverage

**Comment by ozlerhakan** [comment]
what do you think about this implementation @breucode, and @Brutus5000

**Comment by Brutus5000** [comment]
Two minor things first:
1. There is a typo in the package name `parer` (should be `parser`)
2. The new excel file for testing uses camel case, all other file names use snake case.

The PR itself is impressive. I am not sure if I like the approach to override the Locale default as shown in the test. This could have side-effects in other places of my applications. I would prefer to set it as part of the Poiji options.

Overall I was looking and debugging it to find out why this actually works. As a workaround of this issue I wrote a custom validator for spring and it had issues with interpreting the same String value for different Locales, but this PR can do it.
The difference: my validator got the cell value declared as a String and it seems in this case I get my german format, but in this PR even if formatted as german value, the string passed internally seems to be EN locale. This only fails if a user enforces his value to be a string using a leading apostrophe. In this case the casting fails here as well. I do not understand enough about the internals of Apache POI but if we alway get EN locale value, we are good.

Disclaimer: I was unable to get my hands on other localized versions of Excel to cross-test this.

**Comment by hexmind** [comment]
Hi @Brutus5000 and thank you for review.
I override Locale only in tests and always clean up (@After).
We not always get EN locale value. In reality PoijiHandler receive  from POI formattedValue where content depends on JVM Locale. This formattedValue was a reason of failures.

I fixed both mistakes and I will increase tests coverage soon.

**Comment by breucode** [comment]
Looks good from my side 👍. Good job!

**Comment by ozlerhakan** [comment]
This will be about to merge this week :)

**Comment by Brutus5000** [comment]
Thansk about clarification with the formattedValue. If was not avare this depedends on the JVM locale. We tested around and thought it was related to the locale of the Excel version the file was saved with. But the colleague of mine who tested it had his whole machine set to english afaik, even though he is german. I guess this explains the issues we had.

**Comment by ozlerhakan** [comment]
one last thing I need is that could you please update our README if needed  @hexmind ?

**Comment by hexmind** [comment]
I didn't find anything to update in the readme, there are no changes in the API.

**Comment by ozlerhakan** [comment]
thank you  @hexmind merged 🎉

**Pull request merged**
