### PR TITLE
add case insensitive column names support

### LINKED ISSUE #124: Case insensitive column names option
Could you add support of case insensitive column names option please?

 **Example**:

Option:

```PoijiOptions.PoijiOptionsBuilder.settings().caseInsensitive(true);```

Excel table:

| ID     | NamE   |
|--------|--------|
| 123923 | Joe    |
| 123123 | Sophie |
| 135923 | Paul   |

Class:

```
public class Employee {

    @ExcelCellName("id")
    private long employeeId;

    @ExcelCellName("name")
    private String name;

    @Override
    public String toString() {
        return "Employee{" +
                "employeeId=" + employeeId +
                ", name='" + name + '\'' +
                '}';
    }
}
```

Result:

```Employee{employeeId=123923, name='Joe'}```

### PR DESCRIPTION
**Pull request by vaa25**
Resolves #124

### CODE REVIEW

**Comment by vaa25-digis** [comment]
> what about for xls files?

@ozlerhakan Source file extension doesn't matter. Added test for xls.

**Comment by ozlerhakan** [comment]
you should also implement the xls part @vaa25

**Comment by vaa25** [comment]
Yes, I will do it later. There's some problem with unknown fields now. To fix it I need more time.

**Comment by ozlerhakan** [comment]
np take your time @vaa25

**Comment by vaa25** [comment]
@ozlerhakan review please

**Comment by ozlerhakan** [comment]
merged!

**Pull request merged**
