### PR TITLE
Added methods to read excel properties from excel files

### PR DESCRIPTION
**Pull request by breucode**
This PR enables the possibility to read excel properties (but only from XLSX files!).

Solves #151

### CODE REVIEW

**Comment by breucode** [comment]
Currently missing:

- [ ] Unit tests
- [ ] Readme update
- [ ] Proper JavaDocs

**Comment by ozlerhakan** [comment]
Hi @breucode , thanks for the changes! at first glance, we need to improve the code coverage a bit more :)

**Comment by breucode** [comment]
> Hi @breucode , thanks for the changes! at first glance, we need to improve the code coverage a bit more :)

Hi @ozlerhakan :). As far as I can see, the only new untested code are private constructors and exception handling.

Should we add testing for exception handling to Poiji? If we do so, we could add a mocking framework for non-static calls. However, a lot of calls are static (e.g. `OPCPackage.open(...)`), so we either need to find a parameter, which triggers the exception. Alternatively, we need to go a functional way, where we can switch real method with a method, which throws the needed exception.

What would you say @ozlerhakan ?

**Comment by ozlerhakan** [comment]
I think we need to refrain ourselves to use/create static methods.

**Comment by breucode** [comment]
> I think we need to refrain ourselves to use/create static methods.

I agree, but I don't see a way to replace calls like OPCPackage.open(...), which come from an external library.

**Comment by ozlerhakan** [comment]
I will look at it this weekend @breucode

**Pull request merged**
